FROM node:20-alpine

# Install pnpm
RUN pnpm install -g pnpm@11.1.2

# Set the working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY . .

# Expose the port the app runs on
EXPOSE 3000

CMD ["pnpm", "start"]